//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuneSourceSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public string account_id { get; set; }
        public string customer_id { get; set; }
        public string purchase_id { get; set; }
        public int customer_username { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual purchase purchase { get; set; }
    }
}
